### ISSUE TITLE
021 | Som en användare vill jag kunna välja storlek på en produkt

### ISSUE THREAD

**Issue by A-Ozmehak** [Projekt-Grupp-2/ProductProvider#41]
**Tasks:** Camilla
- [x] Skapa komponent sizes
- [ ] Hämta data från productprovider
- [ ] Rendera ut disabled om storlek ej finns i lager 

**Aktivitetsdiagram:** Camilla
![Image](https://github.com/user-attachments/assets/83080e3e-d154-4a62-86c7-e39ea0557531)

**Sekvensdiagram:** Camilla
![Image](https://github.com/user-attachments/assets/f8a00f0b-8ca6-45a2-ac84-24bb3513b7d4)

**Acceptanskriterier:**

**Testfallsbeskrivningar:**
