### ISSUE TITLE
028 | Som en administratör vill jag kunna uppdatera en kategori

### ISSUE THREAD

**Issue by Camilla-bjorkcom** [Projekt-Grupp-2/ProductProvider#5]
**Tasks:** Jonas
- [x]  I ProductProvider lägg till en UpdateCategory funktion för att updatera en kategori
- [x] UpdateCategory kollar om kategorin existerar
- [ ] Om kategorin inte existerar, returneras ett felmeddelande
- [x] Om kategorin existerar, uppdateras informationen om kategorin.
- [x] Förändringen sparas i databasen.
- [ ] När ändringen har sparats, skickas ett meddelande om att den har uppdaterats framgångsrikt.

**Aktivitets Diagram:**

**Sekvens Diagram:** Jonas
![Image](https://github.com/user-attachments/assets/969b2f39-29c2-4848-86c8-fa4497d28365)
**Acceptance Kriterier:**

**Testfallsbeskrivning:**
