### ISSUE TITLE
068 | Som en utvecklare vill jag kunna göra CRUD för en produkt entity

### ISSUE THREAD

**Issue by A-Ozmehak** [Projekt-Grupp-2/ProductProvider#9]
**Tasks: Anna**
- [x] Skapa funktionalitet för CreateProductAsync i ProductProvider
- [x] Skapa funktionalitet för DeleteProductAsync i ProductProvider
- [x] Skapa funktionalitet för GetProductAsync i ProductProvider
- [x] Skapa funktionalitet för UpdateProductAsync i ProductProvider
- [x] Skapa funktionalitet för GetOneProductAsync i ProductProvider
- [x] Produkten ska sparas i databasen när man skapar en ny
- [x] Förändringen ska sparas i databasen vid update
- [x] Förändringen ska sparas i databasen vid delete
- [x] Produkterna/produkten ska hämtas från databasen

**Acceptanskriterier: Anna**

1. CreateProductAsync:
- [x]  Användaren ska kunna skapa en ny produkt genom att ange nödvändiga fält.
- [x] Produkten ska sparas i databasen med korrekt information.
- [x] Skapad produkt ska ha ett unikt ID genererat.

2. DeleteProductAsync:
- [x] Användaren ska kunna ta bort en befintlig produkt baserat på dess ID.

3. GetAllProductsAsync:
- [x] Användaren ska kunna hämta alla produkter från databasen.

4. GetOneProductAsync:
- [x] Användaren ska kunna hämta en specifik produkt genom dess ID.

5. UpdateProductAsync:
- [x] Användaren ska kunna uppdatera en befintlig produkt baserat på dess ID.
- [x] Uppdaterade information ska sparas i databasen.

**Testfallsbeskrivingar: Anna**
1. Testfall 1: Skapa en ny produkt (CreateProductAsync)
  - Förutsättning:
    - Ett korrekt ProductModel skickas in till metoden. 
  - Steg: 
    - Användaren anropar CreateProductAsync-metoden.
  - Förväntat resultat:
    - Produkten skapas och sparas i databasen med ett unikt ID
    - Produkten kan hämtas genom GetOneProductAsync med samma data som skickades in.

2. Testfall 2: Hämta alla produkter (GetAllProductsAsync)
  - Förutsättning:
    - Flera produkter finns i databasen 
  - Steg:
    - Simulera en in-memory databas med några produkter
    - Anropa GetAllProductsAsync-metoden från ProductService.
  - Förväntat resultat:
    -  En lista av produkter returneras med komplett data.
    - Antalet produkter i resultatet överensstämmer med antalet produkter som finns i databasen.

3. Testfall 3: Hämta en produkt (GetOneProductAsync)
  - Förutsättning:
    -  Det finns en produkt med ett unikt ID lagrad i databasen.
  - Steg:
    -  Simulera en in-memory databas med en produkt
    - Anropa GetOneProductAsync-metoden med produktens ID.
  -  Förväntat resultat:
    -  Metoden returnerar en produkt som överensstämmer med den produkt som lagrats i databasen.

4. Testfall 4: Hämta en produkt som inte existerar (GetOneProductAsync)
  - Förutsättning:
    -  Databasen innehåller ingen produkt med det anropade ID
  - Steg:
    -  Skapa en in-memory databas utan att lägga till några produkter.
    - Anropa GetOneProductAsync-metoden med ett unikt ID som inte finns i databasen.
  - Förväntat resultat:
    -  Metoden returnerar null då ingen produkt med det givna ID existerar i databasen.

5. Testfall 5: Uppdatera en produkt (UpdateProductAsync)
    - Förutsättning: 
      - Det finns en produkt i databasen.
    - Steg: 
      - Användaren anropar UpdateProductAsync med ändrade fält.
    - Förväntat resultat:
      - Produkten uppdateras med nya värden i databasen.
      - När produkten hämtas igen via GetOneProductAsync, ska de nya värdena vara sparade korrekt.

6. Testfall 6: Uppdatera en produkt som inte existerar (UpdateProductAsync)
  -  Förutsättning:
    -  Det finns ingen produkt i databasen med det angivna ID.
  - Steg:
    -  Simulera en in-memory databas utan några produkter.
    - Anropa UpdateProductAsync-metoden med ett ID för en produkt som inte existerar i databasen, tillsammans med ändrade fält (till exempel namn, beskrivning, priser osv.).
  - Förväntat resultat:
    -  Metoden returnerar null, eftersom den inte finns i databasen.
    - Inga ändringar görs i databasen.
    
7. Testfall 7: Ta bort en produkt (DeleteProductAsync)
  - Förutsättning: 
    -  En produkt finns i databasen.
  - Steg: 
    - En in-memory databas skapas och en produkt med associerade bilder, priser och lagerstatus läggs till.
    - En mock av IDbContextFactory<DataContext> sätts upp för att returnera den nyss skapade databasen.
    - Användaren anropar DeleteProductAsync med produktens ID
  - Förväntat resultat:
    -  Produkten och alla associerade data ska tas bort från databasen.
    -  Produkten kan inte längre kunna hämtas via GetOneProductAsync.
    
8. Testfall: Ta bort en produkt när produkten inte existerar (DeleteProductAsync)
  -  Förutsättning:
    -  Det finns ingen produkt i databasen med det angivna ID
  - Steg: 
    -  Skapa en in-memory databas utan några produkter.
    - Mocka IDbContextFactory<DataContext> så att den returnerar den skapade databasen.
    - Instansiera ProductService med den mockade databasen.
    - Anropa DeleteProductAsync med ett slumpmässigt ID (ett ID som inte existerar i databasen).
  - Förväntat resultat:
    - Metoden returnerar false, eftersom produkten inte finns i databasen.
